version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'friday'
      groups:
          eslint:
              applies-to: version-updates
              patterns:
                  - "eslint"
                  - "@eslint/js"
          react:
              applies-to: version-updates
              patterns:
                  - "react"
                  - "react-dom"
          next:
              applies-to: version-updates
              patterns:
                  - "next"
                  - "eslint-config-next"
                  - "@next/*"
          jest:
              applies-to: version-updates
              patterns:
                  - "jest"
                  - "jest-environment-jsdom"
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-patch']
