[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "script-src 'self' 'sha256-g/3BALveGEpdkCkH2y/77h1LGKA+x2MiC79foTHfnso=' 'sha256-9RYbJifUPerssoMLMeQ+czknyHjirMOD3crbk0VzmAo=' www.googletagmanager.com"
