[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "script-src 'self' 'sha256-Xx1qH0807TN/B69/HIF7ULKz26Db+v/RzbWst77skfQ=' 'sha256-5kuXmh3p8P/r6hh4pKk6Ky9FIN+5A4nBZqV94KFTs+g=' www.googletagmanager.com; object-src 'none'"
