[build]
    command = "next build"
    publish = ".next"
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "script-src 'self' 'sha256-cFHf0p0kpu3CNX8GxFc8i2hPrYEtNF8qVlRWqgnvvBE=' 'sha256-5kuXmh3p8P/r6hh4pKk6Ky9FIN+5A4nBZqV94KFTs+g=' www.googletagmanager.com; object-src 'none'"

[[headers]]
    for = "/fonts/*"
    [headers.values]
        Cache-Control = '''
        public,
        max-age=365000000,
        immutable'''

[[headers]]
    for = "/images/*"
    [headers.values]
        Cache-Control = '''
        public,
        max-age=604800'''
