[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = "script-src 'self' www.googletagmanager.com"
