name: Tests and checks

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests_and_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install node_modules
        run: npm ci
      - name: Run tests and checks
        run: |
          npm run check
          npm run test
